# Generated by Django 5.2 on 2025-04-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Аты-жөнү')),
                ('email', models.EmailField(max_length=254, verbose_name='Электрондук почтасы')),
                ('message', models.TextField(verbose_name='Билдирүүсү')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Келген убактысы')),
                ('is_read', models.BooleanField(default=False, verbose_name='Окулдубу?')),
            ],
            options={
                'verbose_name': 'Кайрылуу (Байланыш)',
                'verbose_name_plural': 'Кайрылуулар (Байланыш)',
                'ordering': ['-created_at'],
            },
        ),
    ]
