# Generated by Django 5.2 on 2025-04-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='Сүрөтү'),
        ),
    ]
