"""
Django settings for sanarip_project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# sanarip_project/settings.py (ЖАҢЫДАН ТҮЗҮЛГӨН, ТОЛУК КОД)

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/stable/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Ар бир долбоор үчүн уникалдуу ачкыч керек. Муну алмаштыруу сунушталат.
# # Команда: python manage.py shell -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'
# SECRET_KEY = 'django-insecure-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' # АЛМАШТЫРЫҢЫЗ!
import os
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'демейки_өтө_коопсуз_эмес_ачкыч') # Эгер env жок болсо, демейки ачкыч колдонулат (бул жакшы эмес!)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # Иштеп чыгуу учурунда TRUE болушу керек

ALLOWED_HOSTS = [] # Production'до сайттын домен(дер)ин жазыңыз

# Application definition
INSTALLED_APPS = [
    # Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', # Статикалык файлдар үчүн
    # Биздин Тиркеме
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sanarip_project.urls' # Негизги URL конфигурация файлы

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Шаблондорду издөөчү негизги папкалар
        'DIRS': [BASE_DIR / 'templates'],
        # Тиркемелердин ичиндеги 'templates' папкаларын да издөө
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sanarip_project.wsgi.application' # WSGI сервери үчүн


# Database
# https://docs.djangoproject.com/en/stable/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', # SQLite базасы
        'NAME': BASE_DIR / 'db.sqlite3', # База файлынын жайгашкан жери
    }
}


# Password validation
# https://docs.djangoproject.com/en/stable/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# Internationalization
# https://docs.djangoproject.com/en/stable/topics/i18n/
LANGUAGE_CODE = 'ky' # Сайттын тили (Кыргызча)
TIME_ZONE = 'Asia/Bishkek' # Убакыт алкагы (Кыргызстан)
USE_I18N = True # Эл аралыкташтырууну колдонуу
USE_TZ = True # Убакыт алкагын колдонуу


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/stable/howto/static-files/

# Веб даректе статикалык файлдарга жетүүчү URL префикси
STATIC_URL = '/static/'

# Django статикалык файлдарды ИЗДЕЙ турган кошумча папкалар
STATICFILES_DIRS = [
    BASE_DIR / 'static', # Негизги static папкабыз
]

# `collectstatic` командасы файлдарды ЧОГУЛТА турган папка
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Media files (User Uploads)
# https://docs.djangoproject.com/en/stable/topics/files/

# Веб даректе медиа файлдарга жетүүчү URL префикси
MEDIA_URL = '/media/'

# Медиа файлдар сакталуучу негизги папка (файл системасында)
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/stable/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'